version: '3.9'

services:

  traffic-postgresql:
    build: ./docker-postgresql
    container_name: traffic-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=StrongAdminP@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
          - traffic-network

  traffic-api-server:
    build: ./api-server
    container_name: traffic-api-server
    ports:
      - "8080:8080"
    depends_on:
      - traffic-postgresql
    env_file:
      - ./api-server/.docker-env 
    networks:
      - traffic-network

  traffic-bucket:
    image: minio/minio
    container_name: traffic-bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    environment: 
      MINIO_ACCESS_KEY: key12345
      MINIO_SECRET_KEY: pwd12345
    volumes:
      - bucket-data:/data
    networks:
      - traffic-network
    command: server /data --console-address ":9001"

volumes:
  bucket-data:

networks:
  traffic-network:
    driver: bridge

  