version: '3.9'

services:

  traffic-postgresql:
    build: ./docker-postgresql
    container_name: traffic-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=StrongAdminP@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
          - traffic-network

  traffic-api-server:
    build: ./api-server
    container_name: traffic-api-server
    ports:
      - "8080:8080"
    depends_on:
      - traffic-postgresql
    env_file:
      - ./api-server/.docker-env 
    networks:
      - traffic-network

  traffic-bucket:
    image: minio/minio
    container_name: traffic-bucket
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: your_access_key
      MINIO_SECRET_KEY: your_secret_key
    volumes:
      - /path/to/data:/data
    networks:
      - traffic-network

networks:
  traffic-network:
    driver: bridge

  
    
 

