spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}
    username:  ${env.DB_USER}
    password : ${env.DB_PASSWORD}

  batch:
    jdbc:
      initialize-schema: always

server:
  port: ${env.APPLICATION_PORT}

bucket:
  name: ${env.BUCKET_NAME}
  endpoint: ${env.BUCKET_ENDPOINT}
  accessKey: ${env.BUCKET_ACCESS_KEY}
  secretKey: ${env.BUCKET_SECRET_KEY}


