spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}
    username:  ${env.DB_USER}
    password : ${env.DB_PASSWORD}
  jpa:
    database: postgresql

server:
  port: ${env.APPLICATION_PORT}
  servlet:
    context-path: /challenge
